# Makefile defines for building the MiniGUI DLL with Microsoft VC

SUBINC=1

!INCLUDE Makefile.am

!INCLUDE ..\..\..\build\Defs.win32
!INCLUDE ..\..\..\build\makedefs.msvc

libmgextincludedir = $(includedir)\minigui\ext

install::
	@for %d in ($(libmgextinclude_HEADERS)) do $(CP) %d $(libmgextincludedir)\ext\

